### ISSUE TITLE
Help to understand the possibility of supporting jsonargparse and LightningCLI

### ISSUE THREAD

**Issue by mauvilsa** [iterative/shtab#63]
There is some interest in using `shtab` for [jsonargparse](https://github.com/omni-us/jsonargparse) which is an extension of the standard python `argparse`. Even though it is an extension it has advanced features such as automatic creation of parsers from [signatures](https://jsonargparse.readthedocs.io/en/stable/#classes-methods-and-functions) of classes and functions that have arbitrarily complex [type hints](https://jsonargparse.readthedocs.io/en/stable/#type-hints). For example this is used in [LightningCLI](https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_cli.html) a part of [pytorch-lightning](https://github.com/PyTorchLightning/pytorch-lightning) which helps in the creation of CLIs with minimal boilerplate.

Not being familiar with the code base of `shtab` it is difficult to understand the possibilities for supporting jsonargparse and if it will be fast enough for the LightningCLI use case. It would be very helpful to get your thoughts. Please have a look at the following github issue https://github.com/omni-us/jsonargparse/issues/108.

**Comment by casperdcl** [comment]
Will respond on https://github.com/omni-us/jsonargparse/issues/108; happy to re-open issue here should there be any need. Summary:

- `shtab` only requires an `argparse.ArgumentParser`-like object for it to generate completions
- `shtab` is indeed faster than `argcomplete` as it generates shell completions in advance rather than at each `TAB` by default
- should dynamic completions be required (i.e. you need to re-compute completions on pressing `TAB`) you can do so using custom completions, e.g. https://github.com/iterative/shtab/blob/master/examples/customcomplete.py effectively does `ls *.txt` but you could do `some_python_command --list-options` instead.
